export const products = [

    {
        id: 1,
        title: "Campera Braulia",
        price: 120000,
        stock: 8,
        description: "Campera larga de microfibra impermeable matelaseada.",
        more: "Campera larga de microfibra impermeable matelaseada, de silueta entallada y manga larga. Posee capucha y cierres personalizados Markova. Sus recortes combinados hacen que la prenda entalle a la perfección. La mejor opción para los días más fríos.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1689041736/z398NE_1_dyd18a.jpg",
        img1:"https://res.cloudinary.com/davctp85m/image/upload/v1690740947/sabana_Z398NE_0_ff69oe.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690753127/sabana_Z398NE_2_xa2nkr.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690753181/sabana_Z398NE_4_vjv1rv.jpg"
    },
    {
        id: 2,
        title: "Tapado Becky",
        price: 170000,
        stock: 10,
        description: "Tapado premium de paño lana, de silueta entallada.",
        more: "Tapado premium de paño lana, de silueta entallada, cuello alto y manga larga. Posee cierres metálicos personalizados Markova en bolsillos y acceso central. Tan sobrio como elegante, sin duda es el tapado clásico que nunca pasará de moda.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1689041811/Z372VI_1_aspqok.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690748076/sabana_Z372VI_2_tuvpf5.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690840741/Z372VI_4_hellrv.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690840762/Z372VI_5_psqwsc.jpg"
    },
    {
        id: 3,
        title: "Campera Morgan",
        price: 98000,
        stock: 8,
        description: "Campera de microfibra impermeable, de calce entallado.",
        more: "Campera de microfibra impermeable premium, de calce entallado y manga larga. Posee capucha, cierres y broches metálicos dorados Markova. Su interior está forrado en tafeta lisa. Su entalle en cintura es ideal para las que buscan marcar la silueta con una prenda de abrigo.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1689041890/Z393NE_1_y7rcai.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690747664/sabana_Z393NE_2_ty9zeg.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690840855/Z393NE_4_n34ojr.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690840873/Z393NE_6_o9dpjb.jpg"
    },
    {
        id: 4,
        title: "Campera Clover",
        price: 118000,
        stock: 5,
        description: "Campera corta de cuero vegano elastizado matelaseado premium, de silueta relajada.",
        more: "Campera corta de cuero vegano elastizado matelaseado premium, de silueta relajada, manga larga. Posee capucha y cuello alto. Su ruedo es ajustable por lo que permite regular el calce y no deja pasar el frío. Su interior está forrado en satén elastizado al tono. Este ítem de pura tendencia es ideal para tus looks urbanos de invierno.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690734274/Z390MF_1_qrxkar.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690748164/Z390MF_2_qzhn9r.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690841040/Z390MF_4_zqjy52.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690841063/Z390MF_5_b1jhdp.jpg"
    },
    {
        id: 5,
        title: "Tapado Mewis",
        price: 165000,
        stock: 4,
        description: "Tapado premium largo de paño lana, de silueta entallada y manga larga.",
        more: "Tapado premium largo de paño lana, de silueta entallada y manga larga. Posee broches metálicos personalizados Markova. Sus recortes verticales y su largo modular estilizan cualquier look que lo acompañe. Probá combinarlo con una de nuestras faldas o vestidos para lograr un outfit moderno.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690680714/Z380RJ_1_oiwtib.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690747760/sabana_Z380RJ_2_oirphs.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690841353/Z380RJ_5_qocane.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690841374/Z380RJ_6_favk9a.jpg"
    },
    {
        id: 6,
        title: "Tapado Knight",
        price: 175000,
        stock: 4,
        description: "Tapado premium de paño lana de silueta entallada, cruzado y manga larga.",
        more: "Tapado premium de paño lana de silueta entallada, cruzado y manga larga. Posee broches y cierres metálicos personalizados Markova. Un vivo de cierre metálico recorre su solapa para darle un toque rocker pero elegante, este tapado es la apuesta más segura para tu guardarropas.",
        category: "abrigos",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690680628/Z375NE_1_onuhfy.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690747815/sabana_Z375NE_2_fvlf6f.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690848024/Z375NE_4_ztzu1z.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690848036/Z375NE_6_rnfg4a.jpg"
       
    },
    {
        id: 7,
        title: "Pantalón Evelyn",
        price: 58000,
        stock: 10,
        description: "Pantalón de cuero vegano, de tiro alto y pierna slim.",
        more: "Pantalón de cuero vegano, de tiro alto y pierna slim. Posee cinto forrado con hebilla y bolsillos laterales. Un pantalón moderno, versátil y de absoluta tendencia que elevará todos tus looks.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1689042004/Z108NE_1_ktjeqi.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690748403/sabana_Z108NE_2_pye25e.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847239/Z108NE_5_fe3tf9.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847249/Z108NE_4_j747uc.jpg"
    },
    {
        id: 8,
        title: "Pantalón Taylor",
        price: 46800,
        stock: 7,
        description: "Pantalón de sastrería elastizada, de tiro alto y pierna slim",
        more: "Pantalón de sastrería elastizada, de tiro alto y pierna slim. Posee cinto forrado con hebilla y bolsillos laterales. Un pantalón clásico con un twist moderno, ideal para armar un look de oficina. Combinalo con el blazer Taylor y armá el total look.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1689042032/Z103BG_1_xjqjji.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690748487/sabana_Z103BG_2_ft8pvr.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847329/Z103BG_3_kivpso.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847345/Z103BG_4_cnnjwd.jpg"
    },
    {
        id: 9,
        title: "Pantalón Rolfo",
        price: 58000,
        stock: 10,
        description: "Pantalón de cuero vegano, con doble pespunte y bolsillos.",
        more: "Pantalón de cuero vegano, de tiro alto y pierna relajada. Posee recortes con doble pespunte y bolsillos laterales. Su cinto elastizado desmontable con hebilla metálica permite ajustar la cintura para un mejor calce. Fácil de combinar, este ítem será sin duda, un gran aliado de tu guardarropas.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690749525/sabana_Z123AZ_1_j2nrx6.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690749457/sabana_Z123AZ_2_rdssey.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847414/Z123AZ_3_murghe.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847424/Z123AZ_4_vmguer.jpg"
    },
    {
        id: 10,
        title: "Leggings Donk",
        price: 46200,
        stock: 18,
        description: "Leggings en cuero vegano elastizado, de tiro alto y pierna oxford.",
        more: "Leggings en cuero vegano elastizado, de tiro alto y pierna oxford. Posee cierre invisible lateral y tajos en botamangas, perfecto para usar con botas y lograr un look canchero y con mucho estilo.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690671091/sabana_Z195VV_2_u2em6v.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690749321/sabana_Z195VV_3_k7i9eh.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847551/Z195VV_5_zydicn.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847562/Z195VV_6_ogffaf.jpg"
    },
    {
        id: 11,
        title: "Pantalón Bronze",
        price: 44600,
        stock: 9,
        description: "Pantalón de sastrería elastizada, de tiro alto y pierna ancha.",
        more: "Pantalón de sastrería elastizada, de tiro alto y pierna ancha. Posee presillas y botón forrado. Combinalo con el blazer Bronze y armá un total look de absoluta tendencia.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690680791/Z105NE_1_srruss.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690748999/sabana_Z105NE_3_ywo2gc.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847625/Z105NE_6_tk3deu.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847635/Z105NE_5_rh2raq.jpg"
    },
    {
        id: 12,
        title: "Pantalón Bente",
        price: 44600,
        stock: 9,
        description: "Pantalón de bengalina engomada, de tiro alto y pierna slim.",
        more: "Pantalón de bengalina engomada, de tiro alto y pierna slim. Clásico pantalón 5 bolsillos, con un twist: confeccionado en género elastizado con efecto cuero y tajito redondeado en botamangas. Es, sin duda, el pantalón ideal tanto para el día como para una salida.",
        category: "pantalones",
        img: "https://res.cloudinary.com/davctp85m/image/upload/v1690680898/Z121NE_1_bvhrna.jpg",
        img1: "https://res.cloudinary.com/davctp85m/image/upload/v1690749066/sabana_Z121NE_2_uxq4a3.jpg",
        img2: "https://res.cloudinary.com/davctp85m/image/upload/v1690847722/Z121NE_3_ujxjnf.jpg",
        img3: "https://res.cloudinary.com/davctp85m/image/upload/v1690847733/Z121NE_4_mrv0fb.jpg"
    },
]